// scripts/update_frontend.js
// Usage:
//   node scripts/update_frontend.js \
//     --poe 0xPoE \
//     --token 0xToken \
//     --out contracts/out \
//     --front docs

const fs = require('fs');
const path = require('path');

function arg(name, def = undefined) {
    const ix = process.argv.indexOf(`--${name}`);
    return ix !== -1 ? process.argv[ix + 1] : def;
}

const poe = arg('poe');
const token = arg('token');
const outDir = arg('out', 'contracts/out');
const frontDir = arg('front', 'docs');

if (!poe || !token) {
    console.error('❌ Missing --poe or --token address.');
    process.exit(1);
}

const poeJsonPath = path.join(outDir, 'ProofOfEscape.sol', 'ProofOfEscape.json');
const tokenJsonPath = path.join(outDir, 'EscapeToken.sol', 'EscapeToken.json');

function readAbi(jsonPath) {
    const raw = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
    // Foundry artifact format: { abi, bytecode, deployedBytecode, ... }
    if (!raw.abi) {
        console.error(`❌ ABI not found in ${jsonPath}`);
        process.exit(1);
    }
    return raw.abi;
}

// 1) Ensure dest folders
const abiDest = path.join(frontDir, 'abi');
const jsDest = path.join(frontDir, 'js');
if (!fs.existsSync(frontDir)) fs.mkdirSync(frontDir);
if (!fs.existsSync(abiDest)) fs.mkdirSync(abiDest, { recursive: true });
if (!fs.existsSync(jsDest)) fs.mkdirSync(jsDest, { recursive: true });

// 2) Copy *ABI only* (clean, minimal)
const poeAbi = readAbi(poeJsonPath);
const tokenAbi = readAbi(tokenJsonPath);

fs.writeFileSync(path.join(abiDest, 'ProofOfEscape.json'), JSON.stringify(poeAbi, null, 2));
fs.writeFileSync(path.join(abiDest, 'EscapeToken.json'), JSON.stringify(tokenAbi, null, 2));
console.log('✅ Copied ABIs to', abiDest);

// 3) Write frontend config
const configJs = `// Auto-generated by scripts/update_frontend.js
export const CONFIG = {
  CONTRACT_ADDRESS: "${poe}",
  TOKEN_ADDRESS: "${token}",
  CHAIN_ID_HEX: "0x67932", // 424242
  RPC_URLS: ["http://195.251.92.200/rpc/"],
  EXPLORER_URL: "http://83.212.76.39"
};
`;
fs.writeFileSync(path.join(jsDest, 'config.js'), configJs);
console.log('✅ Wrote', path.join(jsDest, 'config.js'));

console.log('🎉 Frontend is synced with latest deploy.');